services:
  - type: web
    name: right-k-app
    env: node
    buildCommand: npm install && npm run build:render
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
